name: flutter_pffastconv
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^8.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_pffastconv
        pluginClass: FlutterPffastconvPlugin
      ios:
        pluginClass: FlutterPffastconvPlugin
ffigen:
  name: 'PFFASTCONVLibrary'
  description: 'Bindings to PFFASTCONVLibrary'
  output: 'lib/generated_bindings.dart'
  llvm-path:
    - 'C:\Program Files\llvm'
  headers:
    entry-points:
      - 'pffastconv.h'
      
  compiler-opts:
    - '"-IC:\Program Files\LLVM\lib\clang\23\include\"'
scripts:
  # bindingクラスを生成する
  ffigen: flutter pub run ffigen